# Note that this project takes place in R

![Two data scientists working on a dashboard.](hr-image-small.png)

A common problem when creating models to generate business value from data is that the datasets can be so large that it can take days for the model to generate predictions. Ensuring that your dataset is stored as efficiently as possible is crucial for allowing these models to run on a more reasonable timescale without having to reduce the size of the dataset.

You've been hired by a major online data science training provider called *Training Data Ltd.* to clean up one of their largest customer datasets. This dataset will eventually be used to predict whether their students are looking for a new job or not, information that they will then use to direct them to prospective recruiters.

You've been given access to `customer_train.csv`, which is a subset of their entire customer dataset, so you can create a proof-of-concept of a much more efficient storage solution. The dataset contains anonymized student information, and whether they were looking for a new job or not during training:

| Column       | Description                                  |
|------------- |--------------------------------------------- |
| `student_id`   | A unique ID for each student.                 |
| `city`  | A code for the city the student lives in.  |
| `city_development_index` | A scaled development index for the city.       |
| `gender` | The student's gender.       |
| `relevant_experience` | An indicator of the student's work relevant experience.       |
| `enrolled_university` | The type of university course enrolled in (if any).       |
| `education_level` | The student's education level.       |
| `major_discipline` | The educational discipline of the student.       |
| `experience` | The student's total work experience (in years).       |
| `company_size` | The number of employees at the student's current employer.       |
| `last_new_job` | The number of years between the student's current and previous jobs.       |
| `training_hours` | The number of hours of training completed.       |
| `job_change` | An indicator of whether the student is looking for a new job (`1`) or not (`0`).       |


The Head Data Scientist at Training Data Ltd. has asked you to create a data frame called ds_jobs_clean that stores the data in customer_train.csv much more efficiently. Specifically, they have set the following requirements: see Q1-Q7.

If you call `object.size()` on `ds_jobs` and `ds_jobs_clean` after you've preprocessed it, you should notice a substantial decrease in memory usage.

In [58]:
#Load packages
library(readr)
library(dplyr)
library(forcats)
library(stringr)

In [59]:
#read in the data
orig_data = read_csv("customer_train.csv")
orig_data

Rows: 19158 Columns: 14
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (10): city, gender, relevant_experience, enrolled_university, education_...
dbl  (4): student_id, city_development_index, training_hours, job_change

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

      student_id city     city_development_index gender relevant_experience
1      8949      city_103 0.920                  Male   Has relevant experience
2     29725      city_40  0.776                  Male   No relevant experience
3     11561      city_21  0.624                  NA     No relevant experience
4     33241      city_115 0.789                  NA     No relevant experience
5       666      city_162 0.767                  Male   Has relevant experience
6     21651      city_176 0.764                  NA     Has relevant experience
7     28806      city_160 0.920                  Male   Has relevant experience
8       402      city_46  0.762                  Male   Has relevant experience
9     27107      city_103 0.920                  Male   Has relevant experience
10      699      city_103 0.920                  NA     Has relevant experience
11    29452      city_21  0.624                  NA     No relevant experience
12    23853      city_103 0.920                  Male   Has relevant experience
13    25619      city_61  0.913                  Male   Has relevant experience
14     5826      city_21  0.624                  Male   No relevant experience
15     8722      city_21  0.624                  NA     No relevant experience
16     6588      city_114 0.926                  Male   Has relevant experience
17     4167      city_103 0.920                  NA     Has relevant experience
18     5764      city_21  0.624                  NA     Has relevant experience
19     2156      city_21  0.624                  NA     Has relevant experience
20    11399      city_13  0.827                  Female Has relevant experience
21    31972      city_159 0.843                  Male   Has relevant experience
22    19061      city_114 0.926                  Male   Has relevant experience
23     6491      city_102 0.804                  NA     Has relevant experience
24     7041      city_40  0.776                  Male   Has relevant experience
25    22767      city_21  0.624                  NA     Has relevant experience
26    14505      city_67  0.855                  NA     No relevant experience
27    17139      city_21  0.624                  NA     Has relevant experience
28    28476      city_103 0.920                  Male   Has relevant experience
29    21538      city_100 0.887                  Male   Has relevant experience
30    10408      city_21  0.624                  Male   Has relevant experience
⋮     ⋮          ⋮        ⋮                      ⋮      ⋮
19129  3365      city_16  0.910                  NA     Has relevant experience
19130  9651      city_100 0.887                  NA     No relevant experience
19131 20668      city_21  0.624                  Male   Has relevant experience
19132 18072      city_116 0.743                  Male   No relevant experience
19133 15549      city_36  0.893                  Male   Has relevant experience
19134 25191      city_10  0.895                  Other  Has relevant experience
19135 28798      city_103 0.920                  Male   Has relevant experience
19136 20520      city_65  0.802                  Male   Has relevant experience
19137 23672      city_21  0.624                  NA     Has relevant experience
19138 22620      city_21  0.624                  NA     Has relevant experience
19139 19765      city_30  0.698                  NA     Has relevant experience
19140  5603      city_21  0.624                  NA     Has relevant experience
19141 11398      city_103 0.920                  NA     No relevant experience
19142  7782      city_23  0.899                  Male   Has relevant experience
19143 13750      city_40  0.776                  Male   Has relevant experience
19144 33047      city_103 0.920                  Male   Has relevant experience
19145 17191      city_21  0.624                  NA     No relevant experience
19146   155      city_44  0.725                  NA     No relevant experience
19147 13167      city_103 0.920                  Male   Has relevant experience
19148 21319      city_21  0.624                  Male   No relevant experience
19149  9212      city_21  0.624                  NA     Has relevant experience
19150   251      city_103 0.920                  Male   Has relevant experience
19151 32313      city_160 0.920                  Female Has relevant experience
19152 11385      city_149 0.689                  Male   No relevant experience
19153 29754      city_103 0.920                  Female Has relevant experience
19154  7386      city_173 0.878                  Male   No relevant experience
19155 31398      city_103 0.920                  Male   Has relevant experience
19156 24576      city_103 0.920                  Male   Has relevant experience
19157  5756      city_65  0.802                  Male   Has relevant experience
19158 23834      city_67  0.855                  NA     No relevant experience
      enrolled_university education_level major_discipline experience
1     no_enrollment       Graduate        STEM             >20
2     no_enrollment       Graduate        STEM             15
3     Full time course    Graduate        STEM             5
4     NA                  Graduate        Business Degree  <1
5     no_enrollment       Masters         STEM             >20
6     Part time course    Graduate        STEM             11
7     no_enrollment       High School     NA               5
8     no_enrollment       Graduate        STEM             13
9     no_enrollment       Graduate        STEM             7
10    no_enrollment       Graduate        STEM             17
11    Full time course    High School     NA               2
12    no_enrollment       Graduate        STEM             5
13    no_enrollment       Graduate        STEM             >20
14    NA                  NA              NA               2
15    Full time course    High School     NA               5
16    no_enrollment       Graduate        STEM             16
17    no_enrollment       Graduate        STEM             1
18    no_enrollment       Graduate        STEM             2
19    no_enrollment       Graduate        STEM             7
20    no_enrollment       Graduate        Arts             4
21    no_enrollment       Masters         STEM             11
22    no_enrollment       Masters         STEM             11
23    no_enrollment       Masters         STEM             10
24    no_enrollment       Graduate        Humanities       <1
25    no_enrollment       Graduate        STEM             5
26    no_enrollment       High School     NA               4
27    Part time course    Graduate        STEM             14
28    no_enrollment       Graduate        Arts             5
29    no_enrollment       High School     NA               11
30    no_enrollment       Graduate        STEM             18
⋮     ⋮                   ⋮               ⋮                ⋮
19129 no_enrollment       Graduate        Humanities       >20
19130 Full time course    Masters         STEM             3
19131 no_enrollment       Graduate        STEM             11
19132 no_enrollment       Masters         STEM             8
19133 no_enrollment       Graduate        STEM             10
19134 no_enrollment       Graduate        STEM             16
19135 Part time course    High School     NA               12
19136 no_enrollment       Graduate        STEM             8
19137 no_enrollment       Masters         STEM             6
19138 no_enrollment       Graduate        STEM             8
19139 no_enrollment       Masters         STEM             11
19140 Full time course    Graduate        STEM             4
19141 no_enrollment       Primary School  NA               2
19142 no_enrollment       Graduate        STEM             17
19143 no_enrollment       NA              NA               5
19144 no_enrollment       Graduate        STEM             >20
19145 Full time course    Graduate        STEM             4
19146 Full time course    Graduate        STEM             5
19147 no_enrollment       Graduate        STEM             5
19148 Full time course    Graduate        STEM             1
19149 no_enrollment       Masters         STEM             3
19150 no_enrollment       Masters         STEM             9
19151 no_enrollment       Graduate        STEM             10
19152 Full time course    Graduate        NA               2
19153 no_enrollment       Graduate        Humanities       7
19154 no_enrollment       Graduate        Humanities       14
19155 no_enrollment       Graduate        STEM             14
19156 no_enrollment       Graduate        STEM             >20
19157 no_enrollment       High School     NA               <1
19158 no_enrollment       Primary School  NA               2
      company_size company_type        last_new_job training_hours job_change
1     NA           NA                  1             36            1
2     50-99        Pvt Ltd             >4            47            0
3     NA           NA                  never         83            0
4     NA           Pvt Ltd             never         52            1
5     50-99        Funded Startup      4              8            0
6     NA           NA                  1             24            1
7     50-99        Funded Startup      1             24            0
8     <10          Pvt Ltd             >4            18            1
9     50-99        Pvt Ltd             1             46            1
10    10000+       Pvt Ltd             >4           123            0
11    NA           NA                  never         32            1
12    5000-9999    Pvt Ltd             1            108            0
13    1000-4999    Pvt Ltd             3             23            0
14    NA           NA                  never         24            0
15    NA           NA                  never         26            0
16    10-49        Pvt Ltd             >4            18            0
17    50-99        Pvt Ltd             never        106            0
18    5000-9999    Pvt Ltd             2              7            0
19    10000+       Pvt Ltd             never         23            1
20    NA           NA                  1            132            1
21    100-499      Pvt Ltd             1             68            0
22    100-499      Pvt Ltd             2             50            0
23    NA           NA                  1             48            0
24    1000-4999    Pvt Ltd             1             65            0
25    1000-4999    Pvt Ltd             1             13            0
26    NA           NA                  never         22            0
27    500-999      Pvt Ltd             1            148            1
28    NA           NA                  2             72            0
29    <10          Pvt Ltd             1              8            1
30    50-99        Funded Startup      2             68            1
⋮     ⋮            ⋮                   ⋮            ⋮              ⋮
19129 1000-4999    Pvt Ltd             >4            23            0
19130 NA           Public Sector       1             30            1
19131 100-499      Pvt Ltd             >4            25            0
19132 10000+       NA                  1             48            0
19133 500-999      Pvt Ltd             1             67            0
19134 10-49        Pvt Ltd             1             36            0
19135 500-999      Pvt Ltd             >4            13            0
19136 50-99        Public Sector       2            136            0
19137 NA           NA                  1              5            1
19138 50-99        Pvt Ltd             >4            80            0
19139 100-499      Pvt Ltd             1             17            0
19140 NA           NA                  NA            13            0
19141 NA           NA                  never         15            0
19142 10-49        Funded Startup      3             12            0
19143 10-49        Early Stage Startup 1             26            0
19144 10000+       Pvt Ltd             >4            18            0
19145 NA           NA                  never         48            1
19146 NA           Pvt Ltd             never        190            0
19147 500-999      Pvt Ltd             1             51            0
19148 100-499      Pvt Ltd             1             52            1
19149 100-499      Pvt Ltd             3             40            1
19150 50-99        Pvt Ltd             1             36            1
19151 100-499      Public Sector       3             23            0
19152 NA           NA                  1             60            0
19153 10-49        Funded Startup      1             25            0
19154 NA           NA                  1             42            1
19155 NA           NA                  4             52            1
19156 50-99        Pvt Ltd             4             44            0
19157 500-999      Pvt Ltd             2             97            0
19158 NA           NA                  1            127            0

In [60]:
#investigate the data
object.size(orig_data)
glimpse(orig_data)

2167296 bytes

Rows: 19,158
Columns: 14
$ student_id             <dbl> 8949, 29725, 11561, 33241, 666, 21651, 28806, 4…
$ city                   <chr> "city_103", "city_40", "city_21", "city_115", "…
$ city_development_index <dbl> 0.920, 0.776, 0.624, 0.789, 0.767, 0.764, 0.920…
$ gender                 <chr> "Male", "Male", NA, NA, "Male", NA, "Male", "Ma…
$ relevant_experience    <chr> "Has relevant experience", "No relevant experie…
$ enrolled_university    <chr> "no_enrollment", "no_enrollment", "Full time co…
$ education_level        <chr> "Graduate", "Graduate", "Graduate", "Graduate",…
$ major_discipline       <chr> "STEM", "STEM", "STEM", "Business Degree", "STE…
$ experience             <chr> ">20", "15", "5", "<1", ">20", "11", "5", "13",…
$ company_size           <chr> NA, "50-99", NA, NA, "50-99", NA, "50-99", "<10…
$ company_type           <chr> NA, "Pvt Ltd", NA, "Pvt Ltd", "Funded Startup",…
$ last_new_job           <chr> "1", ">4", "never", "never", "4", "1", "1", ">4…
$ training_hours         <dbl> 36, 47, 83, 52, 8, 24, 24, 18, 46, 123, 32, 108…
$ job_change             <dbl> 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,…

So, the original dataset has a size of 2,167,296 bytes. It has 19,158 rows.

# Q1
Columns containing integer values must be stored as integers (`<int>`).

In [61]:
#Q1
data <- orig_data

#change data type of 'student_id', 'training_hours', 'job_change' to "int"
data$student_id <- as.integer(data$student_id)
data$training_hours <- as.integer(data$training_hours)
data$job_change <- as.integer(data$job_change)

#could also do 'city' & remove the "city_" prefix
    #data$city <- as.integer(sub("^city_", "", data$city))

glimpse(data)

Rows: 19,158
Columns: 14
$ student_id             <int> 8949, 29725, 11561, 33241, 666, 21651, 28806, 4…
$ city                   <chr> "city_103", "city_40", "city_21", "city_115", "…
$ city_development_index <dbl> 0.920, 0.776, 0.624, 0.789, 0.767, 0.764, 0.920…
$ gender                 <chr> "Male", "Male", NA, NA, "Male", NA, "Male", "Ma…
$ relevant_experience    <chr> "Has relevant experience", "No relevant experie…
$ enrolled_university    <chr> "no_enrollment", "no_enrollment", "Full time co…
$ education_level        <chr> "Graduate", "Graduate", "Graduate", "Graduate",…
$ major_discipline       <chr> "STEM", "STEM", "STEM", "Business Degree", "STE…
$ experience             <chr> ">20", "15", "5", "<1", ">20", "11", "5", "13",…
$ company_size           <chr> NA, "50-99", NA, NA, "50-99", NA, "50-99", "<10…
$ company_type           <chr> NA, "Pvt Ltd", NA, "Pvt Ltd", "Funded Startup",…
$ last_new_job           <chr> "1", ">4", "never", "never", "4", "1", "1", ">4…
$ training_hours         <int> 36, 47, 83, 52, 8, 24, 24, 18, 46, 123, 32, 108…
$ job_change             <int> 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,…

# Q2
Columns containing float values must be stored as doubles (`<dbl>`).

The only column containing floats is 'city_development_index', which is already a "dbl" data type.

# Q3
Columns containing categorical data, both ordinal and nominal, must be stored as factors (`<fct>`).

In [63]:
#Q3
#change 'city', 'gender', 'relevant_experience', 'enrolled_university', 'education_level', 'major_discipline', 'experience',
    #'company_size', 'company_type', 'last_new_job' to a "fct" type
data$city <- as.factor(data$city)
data$gender <- as.factor(data$gender)
data$relevant_experience <- as.factor(data$relevant_experience)
data$enrolled_university <- as.factor(data$enrolled_university)
data$education_level <- as.factor(data$education_level)
data$major_discipline <- as.factor(data$major_discipline)
data$experience <- as.factor(data$experience)
data$company_size <- as.factor(data$company_size)
data$company_type <- as.factor(data$company_type)
data$last_new_job <- as.factor(data$last_new_job)

object.size(data)
glimpse(data)

1176416 bytes

Rows: 19,158
Columns: 14
$ student_id             <int> 8949, 29725, 11561, 33241, 666, 21651, 28806, 4…
$ city                   <fct> city_103, city_40, city_21, city_115, city_162,…
$ city_development_index <dbl> 0.920, 0.776, 0.624, 0.789, 0.767, 0.764, 0.920…
$ gender                 <fct> Male, Male, NA, NA, Male, NA, Male, Male, Male,…
$ relevant_experience    <fct> Has relevant experience, No relevant experience…
$ enrolled_university    <fct> no_enrollment, no_enrollment, Full time course,…
$ education_level        <fct> Graduate, Graduate, Graduate, Graduate, Masters…
$ major_discipline       <fct> STEM, STEM, STEM, Business Degree, STEM, STEM, …
$ experience             <fct> >20, 15, 5, <1, >20, 11, 5, 13, 7, 17, 2, 5, >2…
$ company_size           <fct> NA, 50-99, NA, NA, 50-99, NA, 50-99, <10, 50-99…
$ company_type           <fct> NA, Pvt Ltd, NA, Pvt Ltd, Funded Startup, NA, F…
$ last_new_job           <fct> 1, >4, never, never, 4, 1, 1, >4, 1, >4, never,…
$ training_hours         <int> 36, 47, 83, 52, 8, 24, 24, 18, 46, 123, 32, 108…
$ job_change             <int> 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,…

So far, the size of the dataset has been cut by about 45%.

# Q4
Collapse the `company_size` levels to the following:
- `'Micro'`: <10 employees
- `'Small'`: 10-99 employees
- `'Medium'`: 100-999 employees
- `'Large'`: >1000 employees

In doing so, this variable definitively becomes a nominal category.

In [64]:
#Q4

#first investigate the 'company_size' column
levels(data$company_size)

data <- data %>%
    #collapse old factors into new ones
    mutate(company_size = fct_collapse(company_size, "Micro"=c("<10"), "Small"=c("10-49","50-99"), 
                                       "Medium"=c("100-499","500-999"), "Large"=c("1000-4999","5000-9999","10000+")))
#check new factors
levels(data$company_size)

[1] "<10"       "10-49"     "100-499"   "1000-4999" "10000+"    "50-99"
[7] "500-999"   "5000-9999"

[1] "Micro"  "Small"  "Medium" "Large"

# Q5
Collapse the `experience` levels to the following:
- `'<5'`: <5 year of experience
- `'5-10'`: 5-10 years of experience
- `'>10'`: >10 years of experience

In doing so, this variable definitively becomes a nominal category.

In [65]:
#Q5

#investigate 'experience'
levels(data$experience)

data <- data %>%
    #collapse old factors into new ones
    mutate(experience = fct_collapse(experience,"<5"=c("<1","1","2","3","4"), "5-10"=c("5","6","7","8","9","10"), 
                                     ">10"=c("11","12","13","14","15","16","17","18","19","20",">20")))
#check new factors
levels(data$experience)

 [1] "<1"  ">20" "1"   "10"  "11"  "12"  "13"  "14"  "15"  "16"  "17"  "18"
[13] "19"  "2"   "20"  "3"   "4"   "5"   "6"   "7"   "8"   "9"

[1] "<5"   ">10"  "5-10"

# Q6
The columns of `ds_jobs_clean` must be in the same order as the original dataset.

With the way the data has been manipulated so far, the columns are organized appropriately & do not need any more modification. The only remaining part is officially declaring the variable `ds_jobs_clean`.

In [66]:
#Q6
object.size(data)

1166888 bytes

Recall that the original dataset had a size of 2,167,296 bytes. The data cleaning from Q1-Q6 has reduced the size of the dataset by about 54%.

# Q7
The data frame should be filtered to only contain students with **10 or more years** of experience at companies with **at least 1000 employees**, as their recruiter base is suited to more experienced professionals at large enterprise companies.

In [67]:
#Q7
#filter the data as specified
ds_jobs_clean <- data %>%
    filter(experience == ">10" & company_size == "Large")
ds_jobs_clean
glimpse(ds_jobs_clean)
object.size(ds_jobs_clean)

     student_id city     city_development_index gender relevant_experience
1      699      city_103 0.920                  NA     Has relevant experience
2    25619      city_61  0.913                  Male   Has relevant experience
3    22293      city_103 0.920                  Male   Has relevant experience
4    26494      city_16  0.910                  Male   Has relevant experience
5     2547      city_114 0.926                  Female Has relevant experience
6    25987      city_103 0.920                  Other  Has relevant experience
7     1180      city_16  0.910                  Male   Has relevant experience
8    25349      city_16  0.910                  Male   Has relevant experience
9    20576      city_97  0.925                  Male   Has relevant experience
10    3921      city_36  0.893                  NA     No relevant experience
11   24796      city_103 0.920                  Male   Has relevant experience
12   22718      city_157 0.769                  NA     Has relevant experience
13   12154      city_16  0.910                  NA     Has relevant experience
14   28817      city_89  0.925                  Male   Has relevant experience
15    7280      city_103 0.920                  Male   Has relevant experience
16   16903      city_103 0.920                  Male   Has relevant experience
17   32092      city_103 0.920                  Female Has relevant experience
18   29497      city_103 0.920                  Male   Has relevant experience
19    3728      city_103 0.920                  Male   Has relevant experience
20   26099      city_103 0.920                  Male   Has relevant experience
21   31602      city_103 0.920                  Male   Has relevant experience
22   16814      city_16  0.910                  Male   Has relevant experience
23   33050      city_165 0.903                  NA     Has relevant experience
24   28838      city_103 0.920                  Male   Has relevant experience
25   16537      city_136 0.897                  Male   Has relevant experience
26    4310      city_103 0.920                  NA     Has relevant experience
27   31692      city_160 0.920                  Male   Has relevant experience
28   31401      city_103 0.920                  Male   Has relevant experience
29   24701      city_103 0.920                  NA     Has relevant experience
30   10102      city_103 0.920                  Male   Has relevant experience
⋮    ⋮          ⋮        ⋮                      ⋮      ⋮
1927 30830      city_104 0.924                  Male   Has relevant experience
1928 11531      city_114 0.926                  Male   No relevant experience
1929 10381      city_103 0.920                  NA     Has relevant experience
1930 13921      city_103 0.920                  NA     Has relevant experience
1931 16789      city_28  0.939                  NA     Has relevant experience
1932 28289      city_104 0.924                  NA     Has relevant experience
1933 22825      city_16  0.910                  Male   Has relevant experience
1934 23972      city_75  0.939                  Male   Has relevant experience
1935 21711      city_10  0.895                  Male   Has relevant experience
1936 20603      city_90  0.698                  NA     Has relevant experience
1937 19122      city_103 0.920                  NA     Has relevant experience
1938  3836      city_73  0.754                  Male   Has relevant experience
1939 22184      city_103 0.920                  Female Has relevant experience
1940 30614      city_103 0.920                  NA     Has relevant experience
1941  6401      city_103 0.920                  Male   Has relevant experience
1942 32397      city_103 0.920                  Male   Has relevant experience
1943 26317      city_136 0.897                  Female Has relevant experience
1944 30164      city_160 0.920                  Male   Has relevant experience
1945 24882      city_21  0.624                  Male   Has relevant experience
1946 27394      city_53  0.740                  Male   Has relevant experience
1947 15607      city_16  0.910                  Male   Has relevant experience
1948 12193      city_97  0.925                  Male   Has relevant experience
1949 17005      city_75  0.939                  Male   No relevant experience
1950  7435      city_103 0.920                  NA     Has relevant experience
1951 27838      city_83  0.923                  Male   No relevant experience
1952  2223      city_83  0.923                  NA     Has relevant experience
1953 25447      city_103 0.920                  Male   Has relevant experience
1954 32932      city_10  0.895                  Male   Has relevant experience
1955  3365      city_16  0.910                  NA     Has relevant experience
1956 33047      city_103 0.920                  Male   Has relevant experience
     enrolled_university education_level major_discipline experience
1    no_enrollment       Graduate        STEM             >10
2    no_enrollment       Graduate        STEM             >10
3    Part time course    Graduate        STEM             >10
4    no_enrollment       Graduate        Business Degree  >10
5    Full time course    Masters         STEM             >10
6    no_enrollment       Graduate        STEM             >10
7    no_enrollment       Graduate        STEM             >10
8    no_enrollment       Graduate        STEM             >10
9    no_enrollment       Graduate        STEM             >10
10   no_enrollment       Phd             STEM             >10
11   no_enrollment       Graduate        STEM             >10
12   no_enrollment       Graduate        No Major         >10
13   no_enrollment       Masters         Arts             >10
14   Full time course    Graduate        STEM             >10
15   no_enrollment       Graduate        STEM             >10
16   no_enrollment       Graduate        No Major         >10
17   no_enrollment       Masters         STEM             >10
18   no_enrollment       Masters         STEM             >10
19   no_enrollment       Masters         STEM             >10
20   no_enrollment       Graduate        STEM             >10
21   no_enrollment       Masters         STEM             >10
22   no_enrollment       Graduate        STEM             >10
23   no_enrollment       Graduate        STEM             >10
24   no_enrollment       Graduate        STEM             >10
25   no_enrollment       Masters         STEM             >10
26   no_enrollment       Graduate        STEM             >10
27   Full time course    Graduate        STEM             >10
28   no_enrollment       Masters         STEM             >10
29   no_enrollment       Graduate        STEM             >10
30   no_enrollment       Graduate        STEM             >10
⋮    ⋮                   ⋮               ⋮                ⋮
1927 no_enrollment       Graduate        STEM             >10
1928 no_enrollment       Graduate        STEM             >10
1929 no_enrollment       Graduate        Humanities       >10
1930 no_enrollment       Masters         Business Degree  >10
1931 no_enrollment       Masters         STEM             >10
1932 no_enrollment       High School     NA               >10
1933 no_enrollment       Graduate        STEM             >10
1934 no_enrollment       High School     NA               >10
1935 no_enrollment       Graduate        STEM             >10
1936 no_enrollment       Masters         STEM             >10
1937 no_enrollment       Graduate        STEM             >10
1938 no_enrollment       Graduate        STEM             >10
1939 no_enrollment       Graduate        STEM             >10
1940 no_enrollment       Graduate        STEM             >10
1941 no_enrollment       Graduate        Humanities       >10
1942 no_enrollment       Graduate        STEM             >10
1943 no_enrollment       Masters         STEM             >10
1944 no_enrollment       Graduate        STEM             >10
1945 no_enrollment       Graduate        STEM             >10
1946 no_enrollment       Masters         STEM             >10
1947 no_enrollment       Graduate        STEM             >10
1948 no_enrollment       Masters         STEM             >10
1949 no_enrollment       Graduate        No Major         >10
1950 no_enrollment       Graduate        Arts             >10
1951 no_enrollment       Masters         STEM             >10
1952 no_enrollment       Graduate        STEM             >10
1953 no_enrollment       Graduate        STEM             >10
1954 Part time course    Masters         Other            >10
1955 no_enrollment       Graduate        Humanities       >10
1956 no_enrollment       Graduate        STEM             >10
     company_size company_type  last_new_job training_hours job_change
1    Large        Pvt Ltd       >4           123            0
2    Large        Pvt Ltd       3             23            0
3    Large        Pvt Ltd       >4           141            0
4    Large        Pvt Ltd       3            145            0
5    Large        Public Sector 2             14            0
6    Large        Public Sector 4             52            1
7    Large        Pvt Ltd       1             52            0
8    Large        Pvt Ltd       >4            28            0
9    Large        Pvt Ltd       >4            19            0
10   Large        Public Sector >4             4            0
11   Large        Pvt Ltd       >4            15            0
12   Large        NA            >4            47            0
13   Large        NGO           >4            55            0
14   Large        Pvt Ltd       3            141            1
15   Large        Pvt Ltd       1              6            0
16   Large        Pvt Ltd       1            125            0
17   Large        Pvt Ltd       >4            55            0
18   Large        Public Sector >4            87            1
19   Large        Pvt Ltd       4             13            0
20   Large        Pvt Ltd       1             60            0
21   Large        Pvt Ltd       1              7            0
22   Large        Pvt Ltd       >4            62            0
23   Large        Pvt Ltd       2             12            0
24   Large        NGO           >4            74            0
25   Large        NA            >4           134            0
26   Large        Pvt Ltd       3              4            0
27   Large        Pvt Ltd       1             40            0
28   Large        Pvt Ltd       2            116            0
29   Large        Pvt Ltd       >4            16            0
30   Large        Pvt Ltd       never        107            0
⋮    ⋮            ⋮             ⋮            ⋮              ⋮
1927 Large        Pvt Ltd       >4            37            0
1928 Large        Pvt Ltd       1             97            0
1929 Large        Pvt Ltd       NA            13            1
1930 Large        Pvt Ltd       >4             6            1
1931 Large        Pvt Ltd       3            106            0
1932 Large        Pvt Ltd       4             23            0
1933 Large        Pvt Ltd       1             40            0
1934 Large        Pvt Ltd       >4           178            0
1935 Large        Pvt Ltd       >4            39            0
1936 Large        Public Sector 1              4            0
1937 Large        Pvt Ltd       >4           150            0
1938 Large        Pvt Ltd       >4             6            0
1939 Large        Pvt Ltd       >4            81            0
1940 Large        Pvt Ltd       1             20            0
1941 Large        Pvt Ltd       2            124            0
1942 Large        Pvt Ltd       1             16            0
1943 Large        Pvt Ltd       2             98            0
1944 Large        Public Sector >4            77            0
1945 Large        Pvt Ltd       1             10            1
1946 Large        Public Sector 1             51            0
1947 Large        Pvt Ltd       4             92            0
1948 Large        Pvt Ltd       1             77            0
1949 Large        Pvt Ltd       >4            50            1
1950 Large        Pvt Ltd       >4            54            0
1951 Large        Pvt Ltd       >4            66            0
1952 Large        Pvt Ltd       2             45            0
1953 Large        Pvt Ltd       >4            57            0
1954 Large        Pvt Ltd       >4            18            0
1955 Large        Pvt Ltd       >4            23            0
1956 Large        Pvt Ltd       >4            18            0

Rows: 1,956
Columns: 14
$ student_id             <int> 699, 25619, 22293, 26494, 2547, 25987, 1180, 25…
$ city                   <fct> city_103, city_61, city_103, city_16, city_114,…
$ city_development_index <dbl> 0.920, 0.913, 0.920, 0.910, 0.926, 0.920, 0.910…
$ gender                 <fct> NA, Male, Male, Male, Female, Other, Male, Male…
$ relevant_experience    <fct> Has relevant experience, Has relevant experienc…
$ enrolled_university    <fct> no_enrollment, no_enrollment, Part time course,…
$ education_level        <fct> Graduate, Graduate, Graduate, Graduate, Masters…
$ major_discipline       <fct> STEM, STEM, STEM, Business Degree, STEM, STEM, …
$ experience             <fct> >10, >10, >10, >10, >10, >10, >10, >10, >10, >1…
$ company_size           <fct> Large, Large, Large, Large, Large, Large, Large…
$ company_type           <fct> Pvt Ltd, Pvt Ltd, Pvt Ltd, Pvt Ltd, Public Sect…
$ last_new_job           <fct> >4, 3, >4, 3, 2, 4, 1, >4, >4, >4, >4, >4, >4, …
$ training_hours         <int> 123, 23, 141, 145, 14, 52, 52, 28, 19, 4, 15, 4…
$ job_change             <int> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,…

134768 bytes

The filtered dataset has 1,956 rows, which amounts to 134,768 bytes.